// реэкспорт команд
pub mod attachments;
pub mod audio;
pub mod chat;
pub mod comparisons;
pub mod database;
pub mod folders;
pub mod embeddings;
pub mod export_import;
pub mod presets;
pub mod providers;
pub mod settings;
pub mod ollama;
pub mod search;
pub mod snippets;
pub mod mcp;
pub mod templates;
pub mod tokens;