import {
    IconCode,
    IconPencil,
    IconChartBar,
    IconTerminal2,
    IconBrain,
    IconWand,
    IconRobot,
    IconWorld,
    IconBook,
    IconMath,
    IconPalette,
    IconMusic,
    IconCamera,
    IconShield,
    IconDatabase,
    IconCloud,
    IconBug,
    IconMessageChatbot,
    IconLanguage,
    IconSchool,
    IconBriefcase,
    IconHeartbeat,
    IconScale,
    IconStar,
} from "@tabler/icons-react";
import type { FC } from "react";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SKILL_ICON_MAP: Record<string, FC<any>> = {
    code: IconCode,
    pencil: IconPencil,
    "chart-bar": IconChartBar,
    "terminal-2": IconTerminal2,
    brain: IconBrain,
    wand: IconWand,
    robot: IconRobot,
    world: IconWorld,
    book: IconBook,
    math: IconMath,
    palette: IconPalette,
    music: IconMusic,
    camera: IconCamera,
    shield: IconShield,
    database: IconDatabase,
    cloud: IconCloud,
    bug: IconBug,
    chatbot: IconMessageChatbot,
    language: IconLanguage,
    school: IconSchool,
    briefcase: IconBriefcase,
    heartbeat: IconHeartbeat,
    scale: IconScale,
    star: IconStar,
};

export const SKILL_ICON_OPTIONS = Object.keys(SKILL_ICON_MAP);
